map("n", "<leader>ff", ":Telescope find_files hidden=true <CR>")
map("n", "<leader>fi", ":Telescope live_grep <CR>")
map("n", "<leader>fb", ":Telescope buffers <CR>")
map("n", "<leader>fg", ":Telescope git_status <CR>")
map("n", "<leader>fo", ":Telescope oldfiles <CR>")
map("n", "<leader>fs", ":Telescope lsp_workspace_symbols <CR>")
